###################
# LinkFreetype.cmake #
###################
if(FREETYPE_INCLUDE_DIRS)
  TARGET_INCLUDE_DIRECTORIES(${targetname} PUBLIC ${FREETYPE_INCLUDE_DIRS})
  TARGET_LINK_LIBRARIES(${targetname} PUBLIC ${FREETYPE_LIBRARIES})
#  message("FREETYPE_INCLUDE_DIRS: " ${FREETYPE_INCLUDE_DIRS})
#  message("FREETYPE_LIBRARIES: " ${FREETYPE_LIBRARIES})
  else()
  MESSAGE(WARNING "CANNOT LINK TO FREETYPE SINCE IT WAS NOT FOUND!")
endif(FREETYPE_INCLUDE_DIRS)


